### ISSUE TITLE
Map matching algorithm

### ISSUE THREAD

**Issue by pjhh88** [good-engineer/NAVER-MAP#22]
map matching algorithm

* use distance btw road & position and direction(before -> current)
https://www3.ntu.edu.sg/home/asgeorge/pdf/J04.pdf

* using HMM
http://web.mit.edu/jaillet/www/general/map_matching_itsc2012-final.pdf
https://www.ismll.uni-hildesheim.de/lehre/semSpatial-10s/script/6.pdf

**Comment by good-engineer** [comment]
opend a new issue and explained my thoughts of algorithm implementation

**Comment by pjhh88** [comment]
in https://www.ismll.uni-hildesheim.de/lehre/semSpatial-10s/script/6.pdf

emission probability : gaussian probability
transition probability : exponential probability

**Comment by pjhh88** [comment]
in https://www.mdpi.com/2220-9964/6/11/327/pdf

emission probability: inverse of distance btw road & position/sum of candidate distance inverse
transition probability:
same road = 3/5
connected road = 2/5
separated by one link = 1/5
else = 0

**Comment by pjhh88** [comment]
incremental vitrbi algorithm

https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=4457216
